### ISSUE TITLE
Issues when running this library on AWS lambda

### ISSUE THREAD

**Issue by zgheibali** [ushelp/EasyQRCodeJS#72]
I'm not able to run the library via AWS lambda for some reason
seems that this issue is related to canvas

the error that I get when invoking the lambda:

```
{
  "errorType": "Error",
  "errorMessage": "libuuid.so.1: cannot open shared object file: No such file or directory",
  "trace": [
    "Error: libuuid.so.1: cannot open shared object file: No such file or directory",
    "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Module.require (internal/modules/cjs/loader.js:974:19)",
    "    at require (internal/modules/cjs/helpers.js:93:18)",
    "    at Object.<anonymous> (/var/task/node_modules/canvas/lib/bindings.js:3:18)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
  ]
}
```

Any suggestion on what could be the issue? I tried using lambda layer but it caused a different kind of error.

Thank you in advance

**Comment by venkata-kishore** [comment]
i think you should use the node library for this purpose
